import os
import sys

import pandas as pd

# get the current working directory

sys.path.append('../')
sys.path.append('../toolkit')

print(os.getcwd())
# storiesData = pd.read_csv("../toolkit/stories.csv")

storiesData = pd.read_csv("tools/stories.csv")
from tools.tools import tools

select_story_tools = []

for i in range(len(storiesData)):
    Name = storiesData.loc[i, "StoryName"]
    Description = storiesData.loc[i, "Description"]
    select_story_tools.append(
        {
            "type": "function",
            "function": {
                "name": Name.replace(" ", ""),
                "description": (Name + " : " + Description),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "Example return",
                        },
                        # "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    },

                    # "required": ["location"],
                },
            }
        })
select_story_tools.append(tools[0])
select_story_tools.append(tools[2])
select_story_tools.append(tools[3])
story_type_select = [
    {
        "type": "function",
        "function": {
            "name": "randomStory",
            "description": " The user wants to make their own story. The user would like to generate a story from a few randoms words. The user wants to listen to a story that is generated by a set or random words they provide",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "Example return",
                    },
                    # "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                },

                # "required": ["location"],
            },
        }
    },
    {
        "type": "function",
        "function": {
            "name": "defaultStory",
            "description": " The user doesnt want to make their own stroy but just listen to one .the user want to select a story to listen to from a collection of stories",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "Example return",
                    },
                },
            },
        }
    }
]
story_type_select.append(tools[0])
story_type_select.append(tools[2])
story_type_select.append(tools[3])

if __name__ == "__main__":
    print(sys.path)
    # print(selectStoryTools)
